# Generated by Django 5.2.8 on 2025-11-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporankerusakan',
            name='pelapor',
        ),
        migrations.AddField(
            model_name='laporankerusakan',
            name='kelas',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laporankerusakan',
            name='nama_pelapor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laporankerusakan',
            name='nisn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='kode_barang',
            field=models.CharField(help_text='Bisa pakai nomor unik atau serial number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='laporankerusakan',
            name='status_laporan',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Baru', max_length=20),
        ),
    ]
